default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DB_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('DB_PORT', '5432') %>
  username: <%= ENV.fetch('DB_USERNAME', 'users') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'users') %>

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'users') %>

test:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'users_test') %>

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'users') %>
