version: "3.1"
services:
  postgres:
    image: "postgres:14.6"
    shm_size: 1g
    networks:
      - users-api-network
    ports:
      - "5432:5432"
    restart: always
    command: postgres -c listen_addresses='*' -c max_connections=500
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=users
      - POSTGRES_PASSWORD=users
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U users"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  users-api-network:
    driver: bridge
