version: "3.1"
services:
  postgres:
    image: "postgres:14.6"
    shm_size: 1g
    networks:
      - users-api-network
    ports:
      - "5432:5432"
    restart: always
    command: postgres -c listen_addresses='*' -c max_connections=500
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=users
      - POSTGRES_PASSWORD=users
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U users"]
      interval: 10s
      timeout: 5s
      retries: 5

  database-manager:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/users_api
    networks:
      - users-api-network
    environment:
      - DATABASE_URL=postgres://users:users@postgres:5432/users
    command: bash -c "bundle install && bundle exec rails db:create db:migrate"
    depends_on:
      postgres:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "bundle install && bundle exec puma -C config/puma.rb"
    volumes:
      - .:/users_api
    ports:
      - "3000:3000"
    networks:
      - users-api-network
    environment:
      - DATABASE_URL=postgres://users:users@postgres:5432/users
    depends_on:
      database-manager:
        condition: service_completed_successfully

volumes:
  pgdata:

networks:
  users-api-network:
    driver: bridge
