version: "3.1"
services:
  database-manager:
    build: .
    volumes:
      - .:/users_api
    networks:
      - users-api-network
    environment:
      - DATABASE_URL=postgres://users:users@postgres:5432/users
    command: bash -c "bundle install && bundle exec rails db:create db:migrate"

  web:
    build: .
    command: bash -c "bundle install && bundle exec puma -C config/puma.rb"
    volumes:
      - .:/users_api
    ports:
      - "3000:3000"
    networks:
      - users-api-network
    environment:
      - DATABASE_URL=postgres://users:users@postgres:5432/users
    depends_on:
      - database-manager

networks:
  users-api-network:
    external: true
